name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: |
          echo "Building with Next.js..."
          npm run build
          echo "Build completed. Checking output directory..."
          ls -la
          if [ -d "out" ]; then
            echo "✓ out directory created successfully"
            echo "Contents of out directory:"
            ls -la out/
          else
            echo "✗ Error: out directory not found after build"
            exit 1
          fi

      - name: Add .nojekyll file
        run: |
          echo "Copying .nojekyll file to out directory..."
          cp .nojekyll out/
          echo "✓ .nojekyll file copied successfully"
          echo "Verifying .nojekyll file exists in out directory:"
          ls -la out/ | grep nojekyll || echo "Warning: .nojekyll file not found"

      - name: List output directory
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of out directory:"
          ls -la out/ || echo "out directory does not exist"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4